name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build-image:
    uses: ./.github/workflows/build-image.yml


  call-neuvector-scan:
    needs: call-build-image
    uses: ./.github/workflows/neuvector-scan.yml

  call-mend-scan:
    needs: call-build-image
    uses: ./.github/workflows/mend-scan.yml

  call-trivy-scan:
    needs: call-build-image
    uses: ./.github/workflows/trivy-scan.yml

  call-push-image:
    needs: call-build-image  # Build iş akışı tamamlandıktan sonra Push işlemi yapılacak
    uses: ./.github/workflows/push-image.yml

