name: Full Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: hepapi/devsecops

jobs:
  scan-dockerfile-build-image:
    uses: ./.github/workflows/docker-build.yaml

  neuvector-scan:
    uses: ./.github/workflows/neuvector-scan.yml
    needs: scan-dockerfile-build-image
    with:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ github.sha }}

  mend-scan:
    uses: ./.github/workflows/mend-scan.yaml
    needs: scan-dockerfile-build-image
    with:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ github.sha }}

  trivy-scan:
    uses: ./.github/workflows/trivy-image-scan.yaml
    needs: scan-dockerfile-build-image
    with:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ github.sha }}

  push-image:
    uses: ./.github/workflows/push-image.yaml
    needs: [neuvector-scan, mend-scan, trivy-scan]
    with:
      image_name: ${{ env.IMAGE_NAME }}
      image_tag: ${{ github.sha }}
