name: Neuvector Scan

on:
  workflow_call:

env:
  REGISTRY: docker.io
  IMAGE_NAME: hepapi/devsecops

jobs:
  scan-image-with-neuvector:
    runs-on: ubuntu-latest
    steps:

      - name: Scan Image via NeuVector
        uses: neuvector/scan-action@main
        with:
          image-repository: ${{ env.IMAGE_NAME }}
          image-tag: ${{ github.sha }}
          min-high-cves-to-fail: "150"
          min-medium-cves-to-fail: "150"
          output: csv
