name: Push Docker Image

on:
  workflow_call:

env:
  REGISTRY: docker.io
  IMAGE_NAME: hepapi/devsecops

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pushing multi-architecture image locally
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
