name: Trivy Scan

on:
  workflow_call:

env:
  REGISTRY: docker.io
  IMAGE_NAME: hepapi/devsecops

jobs:
  scan-image-with-trivy:
    runs-on: ubuntu-latest
    steps:

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_PLATFORM: linux/arm64

      - name: Upload Trivy SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy
